CREATE TABLE USUARIO (
    CD_USUARIO              UUID            NOT NULL DEFAULT gen_random_uuid(),
    NM_USUARIO              VARCHAR(100)    NOT NULL,
    TX_EMAIL                VARCHAR(255)    NOT NULL,
    TX_SENHA                TEXT,
    SN_EMAIL_CONFIRMADO     CHAR(1)         NOT NULL DEFAULT 'N',
    TX_TOKEN_CONFIRMACAO    TEXT,
    DT_EXPIRA_CONFIRMACAO   TIMESTAMPTZ,
    TX_TOKEN_SENHA          TEXT,
    DT_EXPIRA_TOKEN_SENHA   TIMESTAMPTZ,
    TX_TEMA                 VARCHAR(20)     NOT NULL DEFAULT 'dark',
    TX_TAMANHO_FONTE        VARCHAR(20)     NOT NULL DEFAULT 'normal',
    SN_ATIVO                CHAR(1)         NOT NULL DEFAULT 'S',
    DT_CADASTRO             TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_USUARIO                  PRIMARY KEY (CD_USUARIO),
    CONSTRAINT CK_USUARIO_EMAIL_CONFIRMADO CHECK (SN_EMAIL_CONFIRMADO IN ('S', 'N')),
    CONSTRAINT CK_USUARIO_ATIVO            CHECK (SN_ATIVO IN ('S', 'N'))
);

-- Parcial para o e-mail de uma conta inativada voltar a ficar livre.
CREATE UNIQUE INDEX UK_USUARIO_EMAIL ON USUARIO (TX_EMAIL) WHERE SN_ATIVO = 'S';

CREATE TABLE CATEGORIA (
    CD_CATEGORIA    UUID            NOT NULL DEFAULT gen_random_uuid(),
    NM_CATEGORIA    VARCHAR(100)    NOT NULL,
    TX_TIPO         VARCHAR(20)     NOT NULL,
    CD_USUARIO      UUID            NOT NULL,
    SN_ATIVO        CHAR(1)         NOT NULL DEFAULT 'S',
    DT_CADASTRO     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_CATEGORIA         PRIMARY KEY (CD_CATEGORIA),
    CONSTRAINT FK_CATEGORIA_USUARIO FOREIGN KEY (CD_USUARIO) REFERENCES USUARIO (CD_USUARIO),
    CONSTRAINT CK_CATEGORIA_TIPO    CHECK (TX_TIPO IN ('RECEITA', 'DESPESA', 'INVESTIMENTO')),
    CONSTRAINT CK_CATEGORIA_ATIVO   CHECK (SN_ATIVO IN ('S', 'N'))
);

CREATE INDEX IX_CATEGORIA_USUARIO ON CATEGORIA (CD_USUARIO);

CREATE TABLE TRANSACAO (
    CD_TRANSACAO    UUID            NOT NULL DEFAULT gen_random_uuid(),
    TX_DESCRICAO    VARCHAR(200),
    VL_TRANSACAO    NUMERIC(18, 2)  NOT NULL,
    TX_TIPO         VARCHAR(20)     NOT NULL,
    DT_TRANSACAO    TIMESTAMPTZ     NOT NULL,
    SN_RECORRENTE   CHAR(1)         NOT NULL DEFAULT 'N',
    CD_USUARIO      UUID            NOT NULL,
    CD_CATEGORIA    UUID            NOT NULL,
    SN_ATIVO        CHAR(1)         NOT NULL DEFAULT 'S',
    DT_CADASTRO     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_TRANSACAO            PRIMARY KEY (CD_TRANSACAO),
    CONSTRAINT FK_TRANSACAO_USUARIO    FOREIGN KEY (CD_USUARIO)   REFERENCES USUARIO   (CD_USUARIO),
    CONSTRAINT FK_TRANSACAO_CATEGORIA  FOREIGN KEY (CD_CATEGORIA) REFERENCES CATEGORIA (CD_CATEGORIA),
    CONSTRAINT CK_TRANSACAO_TIPO       CHECK (TX_TIPO IN ('RECEITA', 'DESPESA', 'INVESTIMENTO')),
    CONSTRAINT CK_TRANSACAO_RECORRENTE CHECK (SN_RECORRENTE IN ('S', 'N')),
    CONSTRAINT CK_TRANSACAO_ATIVO      CHECK (SN_ATIVO IN ('S', 'N'))
);

CREATE INDEX IX_TRANSACAO_USUARIO_DATA ON TRANSACAO (CD_USUARIO, DT_TRANSACAO DESC);
CREATE INDEX IX_TRANSACAO_CATEGORIA    ON TRANSACAO (CD_CATEGORIA);

CREATE TABLE CONTATO (
    CD_CONTATO      UUID            NOT NULL DEFAULT gen_random_uuid(),
    NM_CONTATO      VARCHAR(100)    NOT NULL,
    TX_EMAIL        VARCHAR(255)    NOT NULL,
    TX_MENSAGEM     TEXT            NOT NULL,
    SN_ATIVO        CHAR(1)         NOT NULL DEFAULT 'S',
    DT_CADASTRO     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- Sem IP de propósito, dado pessoal sob LGPD e o Turnstile já barra o abuso.
    CONSTRAINT PK_CONTATO       PRIMARY KEY (CD_CONTATO),
    CONSTRAINT CK_CONTATO_ATIVO CHECK (SN_ATIVO IN ('S', 'N'))
);
