<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Lawllit.Site</RootNamespace>
    <UserSecretsId>649a979c-d7dd-4c07-9d15-c7773364c8b1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lawllit.Repository\Lawllit.Repository.csproj" />
  </ItemGroup>

</Project>
